# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: nightly | Build and release branch

on:
  workflow_dispatch:
  push:
    branches: [ nightly ]

jobs:
  nightly-release:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Get JSON Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'src/module.json'
          prop_path: 'version'
      - name: Prepare Module Manifest
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'src/module.json'
        env:
          version: ${{steps.version.outputs.prop}}
          manifest: https://raw.githubusercontent.com/${{github.repository}}/master/module.json
          download: https://github.com/${{github.repository}}/releases/nightly-${{steps.version.outputs.prop}}/download/lootsheetnpc5e.zip
      - run: npm ci && npm run build --if-present
      - name: Zip files
        run: |
            cd dist
            zip -r ../lootsheetnpc5e .
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: nightly-v${{steps.version.outputs.prop}}
          name: nightly-${{steps.version.outputs.prop}}
          artifacts: 'lootsheetnpc5e.zip'
          draft: false
          prerelease: true
          generateReleaseNotes: true
